In [22]:
from tensorflow.keras.preprocessing.text import one_hot

In [23]:
sent = [
    'I love deep learning',
    'RNNs are great for sequence data',
    'Embeddings help represent words as vectors',
    'I enjoy coding in Python',
    'I am learning about RNNs and embeddings',
    'You can build powerful models with deep learning',
    'We are using TensorFlow and Keras',
    'I like to experiment with neural networks'
]

In [24]:
sent

['I love deep learning',
 'RNNs are great for sequence data',
 'Embeddings help represent words as vectors',
 'I enjoy coding in Python',
 'I am learning about RNNs and embeddings',
 'You can build powerful models with deep learning',
 'We are using TensorFlow and Keras',
 'I like to experiment with neural networks']

In [25]:
## Define a vocabulary size
vocab_size = 10000

In [26]:
## One Hot Representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
one_hot_repr

[[4291, 5747, 3733, 4581],
 [6542, 6751, 9761, 7721, 350, 7929],
 [2541, 1730, 2393, 7124, 1461, 6199],
 [4291, 725, 571, 4593, 1970],
 [4291, 5974, 4581, 5033, 6542, 7981, 2541],
 [7302, 3373, 4295, 2508, 9445, 9709, 3733, 4581],
 [5901, 6751, 3031, 9068, 7981, 5184],
 [4291, 8094, 8874, 6406, 9709, 3970, 4080]]

In [27]:
## Word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import pad_sequences

In [28]:
import numpy as np

In [29]:
sent_length = 8
embedding_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedding_docs)

[[   0    0    0    0 4291 5747 3733 4581]
 [   0    0 6542 6751 9761 7721  350 7929]
 [   0    0 2541 1730 2393 7124 1461 6199]
 [   0    0    0 4291  725  571 4593 1970]
 [   0 4291 5974 4581 5033 6542 7981 2541]
 [7302 3373 4295 2508 9445 9709 3733 4581]
 [   0    0 5901 6751 3031 9068 7981 5184]
 [   0 4291 8094 8874 6406 9709 3970 4080]]


In [40]:
## Feature Representation Dimension
dim = 10

In [46]:
# model = Sequential()
# model.add(Embedding(vocab_size, dim, input_length=sent_length))
# model.compile(optimizer='adam', loss='mse')


model = Sequential()
model.add(Embedding(input_dim=vocab_size, output_dim=dim, input_length=sent_length))
# model.add(SimpleRNN(32))
# model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Build model (optional, but ensures summary works)
model.build(input_shape=(None, sent_length))

In [47]:
model.summary()

Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_9 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [54]:
embedding_docs[0]

array([   0,    0,    0,    0, 4291, 5747, 3733, 4581], dtype=int32)

In [56]:
model.predict(embedding_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step


array([[[ 0.01631174,  0.01667888,  0.0494738 , -0.02095453,
          0.01631664,  0.02984047, -0.01330038, -0.01360757,
          0.00737271, -0.03166927],
        [ 0.01631174,  0.01667888,  0.0494738 , -0.02095453,
          0.01631664,  0.02984047, -0.01330038, -0.01360757,
          0.00737271, -0.03166927],
        [ 0.01631174,  0.01667888,  0.0494738 , -0.02095453,
          0.01631664,  0.02984047, -0.01330038, -0.01360757,
          0.00737271, -0.03166927],
        [ 0.01631174,  0.01667888,  0.0494738 , -0.02095453,
          0.01631664,  0.02984047, -0.01330038, -0.01360757,
          0.00737271, -0.03166927],
        [ 0.02041728,  0.02341658, -0.03577367, -0.02716979,
         -0.04920868, -0.01683499,  0.02201772, -0.01557947,
          0.03606294, -0.04030768],
        [-0.00018072, -0.00732236, -0.0261076 ,  0.03628154,
         -0.01158544, -0.0268188 ,  0.01137168,  0.04322802,
          0.01051475,  0.03811492],
        [ 0.02488781, -0.04258129, -0.01821388,  0.0